# fly.toml app configuration file generated for deploid on 2023-06-21T14:11:37-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deploid"
primary_region = "ams"

[[mounts]]
  source = "data"
  destination = "/app/pb_data"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
