name: Build + Deploy

on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            VITE_SERVER_URL=https://dash.deploid.studio

      - name: Pull
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -i ghcr.io/${{ github.repository }}:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}